### ISSUE TITLE
Judy Griffin is a Democrat and Brian Curran no longer represents District 21 in New York

### ISSUE THREAD

**Issue by digitaltvguy** [openstates/people#112]
Please immediately fix th local representatives for New York State District 21.

If you search zip code for 11570, Brian Curran appears with no district.  He used to represent District 21.

If you search zip code for 11570 Judy Griffin shows up.  This is correct, but she IS A DEMOCRAT

Thank you so much for your wonderful service.

All the best,
Chris

**Comment by joearasin** [comment]
Looks like this is 2 separate issues:

1) In this repo, Judy Griffin has the wrong party
2) In the graphql API, former legislators are being returned with no district (see also, for example, Kampf in 19301)

**Comment by jamesturk** [comment]
#2 should be fixed, I checked a few and they're working now.

**Comment by digitaltvguy** [comment]
Sorry but Judy Griffin is still listed as "Republican".  She is Democrat.

http://www.liherald.com/stories/judy-griffin-unseats-brian-curran-in-21st-assembly-district,108919

https://ballotpedia.org/Judy_Griffin_(New_York)

http://www.nassaucountydems.com/elected-officials/judy-griffin




Thank you,
Chris
