### ISSUE TITLE
All Vermont committees need to be updated -- source URL shows 2018 instead of 2020

### ISSUE THREAD

**Issue by benjamin-brown** [openstates/people#113]
I'm seeing all committees in both chambers showing last session's members on openstates.org.

VT Leg website -- Senate Judiciary Committee
https://legislature.vermont.gov/committee/detail/2020/29/Bill#documents-section

OpenStates -- VT Senate Judiciary Committee
https://openstates.org/vt/committees/judiciary-1cjMZLDRhI3LK9XbjiePlF/

Here's the link referenced on OpenStates' committee page, and it looks like the source of the problem too. The URL shows 2018 instead of 2020.
http://legislature.vermont.gov/committee/loadList/2018.1/    

Here's the correct source link:
https://legislature.vermont.gov/committee/loadList/2020/

The VT legislators and bills on openstates.org look correct as far as I can tell, so I don't see any other issues at this point. Just need to update the committees in both chambers.

**Comment by jamesturk** [comment]
closed in favor of #143
