### ISSUE TITLE
Question on the import process

### ISSUE THREAD

**Issue by showerst** [openstates/people#124]
I followed through step 3 in the README

```
Check for merge candidates using ./scripts/merge.py --incoming tx
```

So now I have data in my _incoming/tx/people directory, but i'm unclear on the next step to properly merge into _data/tx/people without overwriting IDs and extra existing keys.

**Comment by jamesturk** [comment]
There's still a lot of manual stuff, I added some flags like --copy-new, etc. that help with the process but it isn't smart enough to be hands-free yet.

Depending on how close the match is you might be able to do --copy-new & --remove-identical to take care of the two easiest cases.  Typically then I run with --interactive which helps with cases where one thing changed like a photo, that might get you pretty far down the path

**Comment by showerst** [comment]
Cool, thanks I was missing some of those options. I'll try to take a few passes at states soon.
