### ISSUE TITLE
CO: Incorrect Officials

### ISSUE THREAD

**Issue by putorti** [openstates/people#134]
**District 17**
Colorado web site shows [Mike Foote](http://leg.colorado.gov/node/207671)
OpenStates data indicates [Matt Jones](https://leg.colorado.gov/legislators/matt-jones)

**District 9**
Colorado web site shows [Paul Lundeen](https://leg.colorado.gov/legislators/paul-lundeen)
OpenStates data indicates [Kent Lambert](https://openstates.org/person/kent-lambert-5uFSk222byreb9uQLfQfC/)

These are just the ones that users reported so I'm thinking there's potentially more, I'd double check any seats that changed hands.

**Comment by putorti** [comment]
**District 20**
CO Legislator is Incorrect
Colorado web site shows [Jessie Danielson](https://leg.colorado.gov/legislators/jessie-danielson)
OpenStates data indicates [Cheri Jahn](https://leg.colorado.gov/legislators/cheri-jahn)

**Comment by lisabeigel** [comment]
**District 26**
Colorado website shows [Senator Jeff Bridges](http://leg.colorado.gov/node/929346)
OpenStates data indicates [Daniel Kagan](https://openstates.org/person/daniel-kagan-1xux19UysYwB0bU0KQVeOf/)

+13035878303
My state senator resigned and has been replaced. How do I get that updated?
https://rapidbot.io/contact/read/041a45a2-1f36-4b3c-976f-7253db8ee2b8

**Comment by lisabeigel** [comment]
**District 26**
Colorado website shows [Senator Jeff Bridges](http://leg.colorado.gov/node/929346)
OpenStates data indicates [Daniel Kagan](https://openstates.org/person/daniel-kagan-1xux19UysYwB0bU0KQVeOf/)
