### ISSUE TITLE
GA: Scraped House committee names have "&amp;" instead of "&"

### ISSUE THREAD

**Issue by rconnorlawson** [openstates/people#135]
State: GA

Observed on https://openstates.org/ga/committees/?chamber=lower.

Take for example "Banks \&amp; Banking" instead of "Banks & Banking".

**Comment by jamesturk** [comment]
please see #143 - we'd love your input on how you're using committee information and if you'd be willing to help maintain it

**Comment by RandomThis** [comment]
This issue also applies to PA, as seen here: https://openstates.org/pa/committees/

**Comment by rconnorlawson** [comment]
Upon further investigation, I think this issue isn't actually with the data or scrapers, but rather with the way openstates.org is displaying the data. The correct title text (with the "&" character) is present in the yaml files for the GA House Banks & Banking committee mentioned above. I spot-checked several other GA committees and PA committees, which also have the correct data.
