### ISSUE TITLE
CO, CT, FL, GA, IL, IN, LA, MN, MO, NC, OH vacancies

### ISSUE THREAD

**Issue by estaub** [openstates/people#137]
State: CO, CT, FL, GA, IL, IN, LA, MN, MO, NC, OH

The following divisions (districts) appear in old posts of legislators, but do not show in the chamber's `currentMemberships`.  This usually means that they are or were recently vacant.  In my sampling, about half were already filled as of 12 Feb 2019.  A few are missing without any obvious explanation.

CO

* ocd-division/country:us/state:co/sldl:52

CT

* ocd-division/country:us/state:ct/sldu:3
* ocd-division/country:us/state:ct/sldu:5
* ocd-division/country:us/state:ct/sldu:6
* ocd-division/country:us/state:ct/sldl:39
* ocd-division/country:us/state:ct/sldl:99

FL

* ocd-division/country:us/state:fl/sldl:7
* ocd-division/country:us/state:fl/sldl:97

GA

* ocd-division/country:us/state:ga/sldl:176
* ocd-division/country:us/state:ga/sldl:5

IL
* ocd-division/country:us/state:il/sldl:26
* ocd-division/country:us/state:il/sldl:16

IN

* ocd-division/country:us/state:in/sldl:7

LA

* ocd-division/country:us/state:la/sldl:47
* ocd-division/country:us/state:la/sldl:17
* ocd-division/country:us/state:la/sldl:62
* ocd-division/country:us/state:la/sldl:27
* ocd-division/country:us/state:la/sldl:26

MN

* ocd-division/country:us/state:mn/sldu:11

MO

* ocd-division/country:us/state:mo/sldl:158

NC

* ocd-division/country:us/state:nc/sldu:7

OH

* ocd-division/country:us/state:oh/sldl:97

**Comment by jamesturk** [comment]
most of these appear vacant.. but worth looking over

**Comment by estaub** [comment]
@jamesturk Could you take a look at the two I added for IL, see if I'm missing anything?  https://github.com/openstates/people/pull/132

**Comment by nickoneill** [comment]
CA Senate district 1 and 33 are also vacant but currently showing incorrect representatives.

**Comment by jamesturk** [comment]
latest vacancies fixed in @schneidy's PR, closing this in favor of specific issues as they arise 👍
