### ISSUE TITLE
The email addresses for California senators listed on openstates do not work - I get a mailerdemon failure notice every time.

### ISSUE THREAD

**Issue by OCCali** [openstates/people#145]
This is the right template to select if you're reporting an issue with the functionality of OpenStates.org.
If this is a data issue, those are better reported at https://github.com/openstates/openstates where they'll get more attention from the right people.

Example URL: https://openstates.org/<path-to-page>
Browser: 

Please describe the issue:

Please attach a screenshot if applicable!

**Comment by jamesturk** [comment]
After poking around a bit, I don't think they are right.  I'll work to confirm this, but I have a PR ready to remove them.
