### ISSUE TITLE
The Massachusetts legislator phone #s and offices are out of date because they were just reassigned

### ISSUE THREAD

**Issue by JonathanCohn** [openstates/people#150]
Massachusetts state reps & state senators just got new offices over the past couple weeks, so the listed phone numbers and office numbers are (mostly) out-of-date.

**Comment by jamesturk** [comment]
thanks for the heads up, we could use some help with this one if anyone has the time!

**Comment by JonathanCohn** [comment]
Hey James, I have all the info logged in here: https://www.progressivemass.com/ma_legislators_contact. If there's a way for me to help update the site directly, just let me know!
