### ISSUE TITLE
WA State Transportation committees rosters don't match

### ISSUE THREAD

**Issue by peterduniho** [openstates/people#161]
The list of committee members for both the House and Senate Transportation Committees are significantly different from those shown on the State Legislature web site itself.

House Transportation Committee: http://leg.wa.gov/House/Committees/TR/Pages/MembersStaff.aspx

There are 31 members shown, as opposed to the 17 on the openstates.org site, and many of the names on the openstates.org site are not included on the leg.wa.gov list.

Here are the names and email addresses for all 31 members shown on the state list:

Andrew Barkis <andrew.barkis@leg.wa.gov>; Beth Doglio <Beth.Doglio@leg.wa.gov>; Bill Ramos <Bill.Ramos@leg.wa.gov>; Bob McCaslin <Bob.McCaslin@leg.wa.gov>; Carolyn Eslick <Carolyn.Eslick@leg.wa.gov>; Dave Paul <Dave.Paul@leg.wa.gov>; Debra Entenman <Debra.Entenman@leg.wa.gov>; Ed Orcutt <Ed.Orcutt@leg.wa.gov>; Jake Fey <Jake.Fey@leg.wa.gov>; Jared Mead <Jared.Mead@leg.wa.gov>; Javier Valdez <Javier.Valdez@leg.wa.gov>; Jeremie Dufault <Jeremie.Dufault@leg.wa.gov>; Jesse Young <Jesse.Young@leg.wa.gov>; Jim Walsh <Jim.Walsh@leg.wa.gov>; John Lovick <John.Lovick@leg.wa.gov>; Keith Goehner <Keith.Goehner@leg.wa.gov>; Kelly Chambers <Kelly.Chambers@leg.wa.gov>; Lillian Ortiz-Self <Lillian.Ortiz-Self@leg.wa.gov>; Luanne VanWerven <Luanne.VanWerven@leg.wa.gov>; Marcus Riccelli <Marcus.Riccelli@leg.wa.gov>; Matt Boehnke <Matt.Boehnke@leg.wa.gov>; Matt Shea <Matt.Shea@leg.wa.gov>; Mia Gregerson <Mia.Gregerson@leg.wa.gov>; Mike Chapman <Mike.Chapman@leg.wa.gov>; Mike Pellicciotti <Mike.Pellicciotti@leg.wa.gov>; Morgan Irwin <Morgan.Irwin@leg.wa.gov>; Sharon Shewmake <Sharon.Shewmake@leg.wa.gov>; Sharon Wylie <Sharon.Wylie@leg.wa.gov>; Shelley Kloba <Shelley.Kloba@leg.wa.gov>; Tom Dent <Tom.Dent@leg.wa.gov>; Vandana Slatter <Vandana.Slatter@leg.wa.gov>

Likewise...

Senate Transportation Committee: http://leg.wa.gov/Senate/Committees/TRAN/Pages/MembersStaff.aspx

There are 15 members listed on the official state roster, but only 14 on the openstates.org page, and there are an even larger number of legislators on the openstates.org Senate committee list who are not on the official list.

Names and email addresses for the Senate committee members:

Annette Cleveland <Annette.Cleveland@leg.wa.gov>; Claire Wilson <Claire.Wilson@leg.wa.gov>; Curtis King <Curtis.King@leg.wa.gov>; Dean Takko <Dean.Takko@leg.wa.gov>; Emily Randall <Emily.Randall@leg.wa.gov>; Hans Zeiger <Hans.Zeiger@leg.wa.gov>; Joe Nguyen <Joe.Nguyen@leg.wa.gov>; Liz Lovelett <Liz.Lovelett@leg.wa.gov>; Mike Padden <Mike.Padden@leg.wa.gov>; Mona Das <mona.das@leg.wa.gov>; Phil Fortunato <phil.fortunato@leg.wa.gov>; Rebecca Saldaña <Rebecca.Saldana@leg.wa.gov>; Steve Hobbs <Steve.Hobbs@leg.wa.gov>; Steve O'Ban <Steve.OBan@leg.wa.gov>; Tim Sheldon <Timothy.Sheldon@leg.wa.gov>

**Comment by jamesturk** [comment]
see #143
