### ISSUE TITLE
CA Senate District 1

### ISSUE THREAD

**Issue by pcwa-ahendricks** [openstates/people#163]
Ted Gaines Out
Brian Dahle In

https://www.senate.ca.gov/senators?sortbydistrict=ASC

**Comment by pcwa-ahendricks** [comment]
Lower chamber is vacant for District 1

https://www.assembly.ca.gov/assemblymembers?order=field_member_district&sort=asc

**Comment by schneidy** [comment]
@jamesturk 

District 1 in the lower chamber will be vacant until the new year.
