### ISSUE TITLE
Wrong email address for MA State Sen. Becca Rausch

### ISSUE THREAD

**Issue by JonathanCohn** [openstates/people#166]
State Senator Rausch's email address is just becca.rausch@masenate.gov: https://openstates.org/person/rebecca-rausch-7ekOeXPYLP0nzyw4cNGdkX/.

**Comment by JonathanCohn** [comment]
Anyone here?

**Comment by jamesturk** [comment]
if you can submit a PR that would be great, otherwise we'll get to this in
the next batch of updates

**Comment by JonathanCohn** [comment]
Thanks! What would be the proper coding for this in the PR drop-downs?

**Comment by jamesturk** [comment]
Sorry not sure I understand the question

**Comment by JonathanCohn** [comment]
Think I figured it out. Thanks!
