### ISSUE TITLE
PA: Senators not updating

### ISSUE THREAD

**Issue by Deskimo** [openstates/people#190]
We’ve had a report that ex-Senators (Don White for e.g.) are in the data for PA and on investigation i can see that is the case:

Open States has Don C White:
https://openstates.org/person/donald-c-white-5Q9GwMRKn7m9y08kuIAVA4/

Yet no Don White here: https://www.legis.state.pa.us/cfdocs/legis/home/member_information/mbrList.cfm?Body=S

Also  Richard L. Alloway.

Could be others. 

@jamesturk is this where i should report such an issue?

**Comment by schneidy** [comment]
Fixed with #193

**Comment by jamesturk** [comment]
@schneidy looks good so far, can you compare our Senate roster vs. the one on pa.gov to see if there are likely others that are bad?  We'd gotten a few reports of this & I'd like to try to ensure we're up to date
