### ISSUE TITLE
WA: My Representatives are wrong.

### ISSUE THREAD

**Issue by WallbrownF** [openstates/people#210]
What you have...
![2019_12_20_14_48_45_Find_Your_State_Legislators_Open_States_Opera](https://user-images.githubusercontent.com/1015986/71297498-8c777080-2338-11ea-9bdd-0d8da19c0313.png)

What the state website has...
![2019_12_20_14_49_39_Washington_State_Legislature_Opera0](https://user-images.githubusercontent.com/1015986/71297515-9c8f5000-2338-11ea-9b8f-6496bcd32c69.png)

**Comment by jamesturk** [comment]
Thanks for the issue, we'll take a look

**Comment by WallbrownF** [comment]
Welcome
--
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 12/22/19, 08:59 James Turk <notifications@github.com> wrote:

  Thanks for the issue, we'll take a look

**Comment by schneidy** [comment]
@jamesturk Should be updated as it ties into issue #239
