### ISSUE TITLE
Contact note fields should have a vocabulary of valid values.

### ISSUE THREAD

**Issue by estaub** [openstates/people#212]
@heyitsolivia @jamesturk @mileswwatkins 
See https://github.com/openstates/new-openstates.org/issues/55.  I've struggled with this too, bemoaning the messiness of the `note` values.  IMHO, the set of valid values should be in an object somewhere, and set on a contact instance by a reference to an object property (`contactNoteValues.districtOffice`), not as a string literal. 

I could take this on, if it seems right.  

Where would be the right place for the vocabulary object to live?  Does it even belong in openstates, or in pupa?  Should the 

Should I wait till after scraper season has wound down (~February) to avoid merges?

**Comment by jamesturk** [comment]
current values
```
Forney Office
capitol
District Address
District Office Phone
Physical Office
District Phone
Business Phone
District Office
Capitol office
District Office Fax
District Office #3
Capitol Office Phone
County Office
Capitol Office #1
District Email
Home Phone
Capitol Office
District Office #1
Capitol Address
Athens Office
E-mail
district
Springs Office
District Office #2
Senate Office
```

proposed normalized list:
```
District Office
Business Office
Home
Capitol Office
```

**Comment by jamesturk** [comment]
after looking at the actual cases of Business & Home, we can consolidate down to District & Capitol, doing this first, will introduce follow up in #226
