### ISSUE TITLE
Do Legislators list include newly elected Reps for 2020? 

### ISSUE THREAD

**Issue by jrrreynolds** [openstates/people#218]
Are newly elected (2020 sitting congress) reflected? - In Virginia, the attached csv, now pdf, is the [Virginia House of Delegates Member Listings](https://virginiageneralassembly.gov/house/members/members.php). Newly elected reps. (e.g. Avoli, Helmer) are not on Open States' list of [Virginia Legislators](https://openstates.org/va/legislators/).

[memberListExport.pdf](https://github.com/openstates/people/files/4026812/memberListExport.pdf)

**Comment by jamesturk** [comment]
Not quite yet, they will very soon

**Comment by jamesturk** [comment]
VA reps updated, new issue tracking the others at #222
