### ISSUE TITLE
2019 Elections

### ISSUE THREAD

**Issue by jamesturk** [openstates/people#222]
- [x] MS
- [x] VA
- [x] NJ - not updated yet
- [x] KY (special only)
- [x] LA (not updated yet, check for http://house.louisiana.gov/H_Reps/members.aspx?ID=1 Jim Morris retirement)

**Comment by bfeldman89** [comment]
Thanks for doing this, @jamesturk! It looks like the freshmen legislators for MS weren't added at the time of your update. Idk how to do it, or I would. There may be a lag in the MS House (e.g., the [link ](http://billstatus.ls.state.ms.us/members/house/summers.xml) for freshman Rep. Zakiya Summers's bio results in a 404), but the Senate's page appears updated (e.g., freshman Sen, Jeff Tate's [link ](http://billstatus.ls.state.ms.us/members/senate/tate.xml) works).

**Comment by jamesturk** [comment]
@schneidy while you're on legislators today/tomorrow can you check if MS legislators are updated now and also run LA

reminder on running a scrape & importing it- https://docs.openstates.org/en/latest/contributing/people.html#updating-an-entire-state-via-a-scrape

**Comment by schneidy** [comment]
@jamesturk Just ran LA and MS. There was massive turnover in MS.
