### ISSUE TITLE
Wrong legislators

### ISSUE THREAD

**Issue by kwyd** [openstates/people#237]
Despite "being scraped nightly," the following Washington State Legislators are incorrect. This updated data is from the leg.wa.gov listing of legislators as of right now.

House:
District 1: Dereck Stanford -> **Davina Duerr**
District 30: Kristen Reeves -> **Jessee Johnson**
District 40 Jeff Morris -> **Alex Ramel**

Senate:
District 1: Guy Palumbo -> **Derek Stanford**
District 10: Barbara Bailey -> **Ron Muzzall**

Is there an easier method to doing updates than having to check everything out, install a local database, correct the records and check it all back in? That seems like a lot to do when i only have a chrome book.

Thank you for all your hard work at making this data available to folks.

**Comment by jamesturk** [comment]
Thanks for the report, we'll look into it and get a fix ready.

You can submit PRs to the people files in this repo as described in the
documentation (
https://docs.openstates.org/en/latest/contributing/people.html), but it
does require installing  some tooling, but not a database.

For small fixes this can even be done from the web interface, but new
legislators do require a bit more.

**Comment by kwyd** [comment]
Thanks for the speedy reply. =D I will cop to only browsing the steps in the version control howto and skipping to making a comment here.

I was inartfully trying to advocate for a way to update records that less techy folks could use because #effort- i'll go do some reading for next time.

Again, thanks for your attention.
