### ISSUE TITLE
MS: State officials incorrect

### ISSUE THREAD

**Issue by putorti** [openstates/people#249]
**House District 84**

Openstates: [William Shirley](https://openstates.org/person/william-shirley-2isLE4wRjTPDxpwchhjdJq/)
Actual: [Troy Smith](http://billstatus.ls.state.ms.us/members/house/smith.xml)

**Comment by putorti** [comment]
**Senate District 31**

Openstates: [Terry Burton](https://openstates.org/person/terry-c-burton-7DvGMphiDZGzngJJZSlwKh/)
Actual: [Tyler McCaughn](http://billstatus.ls.state.ms.us/members/senate/mccaughn.xml)

**Comment by putorti** [comment]
I'm not certain how many of these are wrong, these are just the ones I saw, but I'd check any districts that changed in the 2019 elections.

**Comment by jamesturk** [comment]
fixed now 👍
