### ISSUE TITLE
Many state CSVs: Missing current members

### ISSUE THREAD

**Issue by andrewbtp** [openstates/people#276]
It looks like the API is updated for these districts, but the bulk CSVs aren't.

State: Connecticut, Illinois, Missouri, North Carolina, Pennsylvania

CSVs are missing:
ct/sldl:39
ct/sldl:99
ct/sldu:3
ct/sldu:5
ct/sldu:6
il/sldu:11
mo/sldl:34
mo/sldu:3
mo/sldu:7
mo/sldu:9
nc/sldu:7
pa/sldu:48

**Comment by jamesturk** [comment]
thanks for the heads up, realized it was a config issue.  new CSVs incoming

**Comment by jamesturk** [comment]
fixed and now nightly runs work again, thanks for catching that
