### ISSUE TITLE
retire.py script is not working with specified name and person id

### ISSUE THREAD

**Issue by PrinceCarter** [openstates/people#282]
docker-compose run --rm people ./scripts/retire.py 2019-09-17 Dan-Bishop-aeda3016-da15-448e-9ae4-62da790b3129.yml

i was trying to clean the data but the person is retired and I was unable to remove him.

here is the error I got: 

Usage: retire.py [OPTIONS] END_DATE FILENAME
Try 'retire.py --help' for help.

Error: Missing argument 'END_DATE'.

I tried other configs for the command but it didn’t work.

**Comment by jamesturk** [comment]
Thanks for this report, I'll take a look.

**Comment by jamesturk** [comment]
I can't reproduce this error- is there anything unusual about your
environment?
