### ISSUE TITLE
100 % of Florida House reps missing email addresses 

### ISSUE THREAD

**Issue by Deskimo** [openstates/people#284]
All of the  Reps in the House have no emails.

for eg. https://openstates.org/person/david-silvers-5ZixIbswudeGlnkJZUCw9V/

currnetly the https://www.myfloridahouse.gov/. gets an error when trying to view.

**Comment by jamesturk** [comment]
looking at their official pages, I am not sure they have email addresses

that isn't uncommon, as it seems they have switched to webforms 
e.g. https://www.myfloridahouse.gov/Sections/Representatives/contactmember.aspx?MemberId=4640&SessionId=89
