### ISSUE TITLE
Standardize/document approach to contacts/offices

### ISSUE THREAD

**Issue by joearasin** [openstates/people#32]
There seem to be inconsistent approaches to whether an item in the list of contacts is an office or a particular method of contact. Is there one approach that should be standardized on?

Compare:
https://github.com/openstates/people/blob/bb55cd3e6efddae6aaf3a90122fbf5df76e99a31/data/ak/people/Mike-Chenault-f7397012-9df3-4efb-b51e-b96ed3fd8fc9.yml#L11-L21
to 
https://github.com/openstates/people/blob/bb55cd3e6efddae6aaf3a90122fbf5df76e99a31/data/al/people/Greg-J-Reed-1f20eba9-8e3a-4042-8a3b-5717029f6c0b.yml#L11-L15

**Comment by jamesturk** [comment]
I'd say the latter is preferred as it makes it possible to group them, the scrapers were a bit inconsistent here though

**Comment by joearasin** [comment]
Along these lines, is "note" the right way to handle the description, or would it make sense to add a bit of schema to differentiate Capitol and District? Here are the distinct values for note:

```
Capitol Office Phone
Capitol office
Capitol Office #1
District Office Fax
District Address
Business Phone
Springs Office
District Office #3
capitol
Capitol Office
E-mail
District Office Phone
District Phone
District Email
Senate Office
District Office #2
Physical Office
District Office
Capitol Address
<null>
district
Home Phone
District Office #1
Capitol Office Fax
```

**Comment by jamesturk** [comment]
note has now been consolidated to Capitol & District Office
