### ISSUE TITLE
Update ME

### ISSUE THREAD

**Issue by showerst** [openstates/people#35]
Maine is already in session with 2019 legislators, but the openstates people scraper is broken for the house.  

I'm working on it over at https://github.com/openstates/openstates/tree/tim/2018/me-2019-people and expect to knock it out in the next few days, just filing this as a tracking bug.

**Comment by csnardi** [comment]
@jamesturk What's the plan for updating this repo with new legislators for the 2019 sessions? Is there going to be some mass update from scrapers, or will it have to be a divided strategy among volunteers?

**Comment by jamesturk** [comment]
just added #38 to track the work, but it'll be a mix of scraping/manual updating
