### ISSUE TITLE
Updates for 2019

### ISSUE THREAD

**Issue by jamesturk** [openstates/people#38]
Akin to openstates/openstates#2681 this is the master ticket for 2019 updates
Right now the process is a bit rough, but described here: https://github.com/openstates/people#updating-an-entire-state-via-a-scrape

Please reference this issue in any PRs 🙂 

Remaining States as of 1/16:
- [x] Alaska 
- [x] Connecticut
- [x] Florida
- [x] New Mexico
- [x] North Carolina - legislator pages 500ing as of 1/3
- [x] Oregon
- [x] Washington 

Completed:
- [x] Alabama
- [x] Arizona
- [x] Arkansas
- [x] California 
- [x] Colorado 
- [x] Delaware
- [x] District of Columbia
- [x] Georgia 
- [x] Hawaii
- [x] Idaho
- [x] Illinois
- [x] Indiana
- [x] Iowa 
- [x] Kansas
- [x] Kentucky
- [x] Louisiana
- [x] Maine 
- [x] Maryland 
- [x] Massachusetts 
- [x] Michigan
- [x] Minnesota
- [x] Mississippi 
- [x] Missouri
- [x] Montana
- [x] Nebraska
- [x] Nevada 
- [x] New Hampshire
- [x] New Jersey
- [x] New York
- [x] North Dakota 
- [x] Ohio
- [x] Oklahoma 
- [x] Pennsylvania
- [x] Puerto Rico
- [x] Rhode Island 
- [x] South Carolina
- [x] South Dakota
- [x] Tennessee 
- [x] Texas
- [x] Utah 
- [x] Vermont
- [x] Virginia
- [x] West Virginia 
- [x] Wisconsin - 2017 data as of 1/3
- [x] Wyoming

**Comment by jamesturk** [comment]
worth noting:
2018 House-only: KS, MN, NM, SC 
2018 No elections: LA, MS, NJ, VA
(we should still check them as there are likely a few specials)

**Comment by jamesturk** [comment]
DC is all incumbents, all good

**Comment by jamesturk** [comment]
thanks a ton for all the help so far @csnardi - if you're working on any and want to comment here to claim them that'd be great so we don't duplicate effort 😄

**Comment by nickoneill** [comment]
Hi there - if I wanted to get started helping out to scrape some states in, which state should I start with to not step on anyone else's toes?

**Comment by csnardi** [comment]
I don't have any state in progress right now, so you're probably good to start wherever!

**Comment by nickoneill** [comment]
Cool, I will take a look at Nevada this afternoon.

**Comment by nickoneill** [comment]
NV is throwing 500 errors on the endpoints that were previously used. The website seems to display the latest reps though, so the scraper might need an update. I'm going to try to find a first state that works before I dive into editing a scraper.

WA seems like it runs using `docker-compose run --rm scrape wa --fastmode --scrape`, but only produces empty json files:

```
Starting openstates_database_1 ... done
loaded Open States pupa settings...
wa (scrape)
19:32:35 INFO pupa: save jurisdiction Washington as jurisdiction_ocd-jurisdiction-country:us-state:wa-government.json
19:32:35 INFO pupa: save organization Washington State Legislature as organization_52aa27f8-0f8e-11e9-8c2b-0242ac140003.json
19:32:35 INFO pupa: save organization Senate as organization_52aa2e2e-0f8e-11e9-8c2b-0242ac140003.json
19:32:35 INFO pupa: save organization House as organization_52aa3162-0f8e-11e9-8c2b-0242ac140003.json
wa (scrape)
jurisdiction scrape:
  duration:  0:00:00.022996
  objects:
    jurisdiction: 1
    organization: 3
```

Going through the scraper contributing guide, it says after this stuff "And then the actual data scraping begins" with logged GET requests and whatnot. It doesn't seem like it's doing that at all. Any idea where to start to debug this?

**Comment by jamesturk** [comment]
@nickoneill WA might need scraper updates too, it might be a small change to the page that is causing us to miss whatever data is there  -- I can take a look at one of those if you want to move on to try to find one that runs without issue for now

**Comment by jamesturk** [comment]
also, possibly of interest to you guys (& anyone else looking to take a crack at this)  I added a few command line flags to the merge script

```
  --remove-identical / --no-remove-identical
                                  In incoming mode, remove identical files.
  --copy-new / --no-copy-new      In incoming mode, copy brand new files over.
  --interactive / --no-interactive
                                  Do interactive merges.
```
these are all fairly experimental right now, but Colorado was a lot faster when I ran with

```--copy-new --remove-identical ``` the first time

and then ```--interactive``` after that to take care of the rest (you should hit a to abort when the merge candidates get really bad)  

it got me about 85% of the way there without a ton of manual file moving/etc.

**Comment by nickoneill** [comment]
@jamesturk Thanks, I mostly wanted to check that I wasn't missing something really obvious. I will dig around for something that works on its own for starters.

**Comment by jamesturk** [comment]
np, working on SD now (just a heads up)

**Comment by nickoneill** [comment]
Ah, I didn't realize I had to manually request `people` to get it to fetch them. I'm moving forward on AZ, will open a PR with more questions about how the person merge process works.

**Comment by nickoneill** [comment]
Actually more questions here first: I ran the merge helper and have some assumptions about what to do next:

For people who are the same (like this with a 0.70 score), update the file in the data directory.
`0.70 data/az/people/Ben-Toma-6d71c8d3-c677-4f4b-96eb-411fbc464c2c.yml incoming/az/people/Ben-Toma-74b10855-2da0-4a63-bf6a-620c8ab4a6e8.yml`

* Why do they have new IDs? Which one should I keep?

For people who are not the same (like this with a 0.10 score), move the unused file to `retired` and add the new file?
`data/az/people/Ken-Clark-a4d3ecd4-8bfc-4e6c-8290-a557bc347680.yml incoming/az/people/Amish-Shah-0147aaf4-bd4a-4a55-8003-684e3e60f522.yml`

**Comment by jamesturk** [comment]
working on Maine now

**Comment by jamesturk** [comment]
MT needs a new scraper, I'm working on it

**Comment by nickoneill** [comment]
Oregon no longer requires API auth (I emailed them about it) and the scraper works great without it, but the website information is out-of-date as of 1/6/2019.

**Comment by nickoneill** [comment]
Washington has not been updated, they convene on January 14th 2019

**Comment by jamesturk** [comment]
taking another swing at NH next

**Comment by jamesturk** [comment]
AK finishes the batch, still tweaks to make but closing this in favor of individual issues as we go
