### ISSUE TITLE
Speed up to_database.py

### ISSUE THREAD

**Issue by csnardi** [openstates/people#55]
The deploy job with `to_database.py` keeps timing out. I'm going to try and speed this up so that all states will be updated, but if anyone has any ideas on where to improve that would be helpful. It looks like most of the time is spent in `update_subobjects()`, and I'm going to look towards `select_related()` for a possible solution.

**Comment by jamesturk** [comment]
Thanks for taking a look- there's definitely optimization to be done.
Travis is a bit limiting in terms of time so my plan was to start running
it on our ECS cloud instead of Travis (and to get us through January to run
it locally on updated states) but if you find major speedups that'd be
great.

**Comment by jamesturk** [comment]
going to do away w/ on-commit deploys for now, there's now a cron running in our scraping infrastructure to do this at least once a day
