### ISSUE TITLE
id/filename stability

### ISSUE THREAD

**Issue by joearasin** [openstates/people#58]
I noticed this change in a recent commit -- Steven Haugaard's file was renamed but the ID stayed consistent (but different from the filename): https://github.com/openstates/people/pull/57/commits/fe6f778a01edbec574c032ce249057c36eefec81#diff-551adae00b923410b40e5bd7fe38b8a6

What can we expect going forward to be the behavior with regards to filenames and IDs? Trust the ID in the contents of the file  to be stable (but not the filename)?

**Comment by jamesturk** [comment]
oops nice catch! that was a mistake when merging- we should add that to the linter to prevent it from happening

**Comment by jamesturk** [comment]
fixed 👍
